name: linkedin_login
description: Library for login with LinkedIn OAuth V2 service. This library helps you to implement authorization with LinkedIn OAuth API's.
version: 2.2.2-beta.1
homepage: https://github.com/d3xt3r2909/linkedin_login
repository: https://github.com/d3xt3r2909/linkedin_login
documentation:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  meta: ^1.9.1
  rxdart: ^0.27.7
  uuid: ^3.0.7
  webview_flutter: ^4.2.1
  webview_flutter_android: ^3.7.1
  webview_flutter_wkwebview: ^3.4.4

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  test: ^1.19.5
  flutter_lints: ^2.0.1

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/linked_in_logo.png
